name: ds_flutter
description: Deadly simple flutter stuff
version: 0.0.1
repository: https://github.com/uac-nhan-nguyen/ds_packages
environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
