name: ds_flutter
description: Deadly simple flutter stuff
version: 0.0.2
repository: https://github.com/uac-nhan-nguyen/ds_packages
environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  ds_fquery: ^0.0.1
  ds_future: ^1.0.7
  gap: ^3.0.1


