name: ds_fquery
description: fork version of fquery that fix double requests on web
version: 0.0.1
repository: https://github.com/41y08h/fquery

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fast_immutable_collections: ^10.2.2
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^4.0.0
  test: ^1.16.0