name: ds_json
description: Deadly simple json object accessor
version: 1.5.2
repository: https://github.com/uac-nhan-nguyen/ds_packages
environment:
  sdk: '>=3.6.2 <4.0.0'
resolution: workspace

dependencies:
  http:
  test: ^1.22.1