name: ds_future
description: Deadly simple future methods
version: 1.0.8
repository: https://github.com/uac-nhan-nguyen/ds_future
environment:
  sdk: '>=3.6.2 <4.0.0'
resolution: workspace

dependencies:
  test: ^1.22.1

