name: ds_collection
description: Deadly simple collection extension
version: 1.0.1
repository: https://github.com/uac-nhan-nguyen/ds_collection
environment:
  sdk: '>=3.6.2 <4.0.0'
resolution: workspace

dependencies:
  test: ^1.22.1
  collection: ^1.17.0

